const data = [
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 1,
    gaps: "no",
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 2,
    healthScore: 3,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 87.42,
    extendedIngredients: [
      {
        id: 9003,
        aisle: "Produce",
        image: "apple.jpg",
        consistency: "SOLID",
        name: "apple",
        nameClean: "apple",
        original: "1 apple",
        originalName: "apple",
        amount: 1.0,
        unit: "",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 1.0,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 19911,
        aisle: "Cereal",
        image: "maple-syrup.png",
        consistency: "LIQUID",
        name: "maple syrup",
        nameClean: "maple syrup",
        original: "1 tsp maple syrup",
        originalName: "maple syrup",
        amount: 1.0,
        unit: "tsp",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
          metric: {
            amount: 1.0,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
        },
      },
      {
        id: 2010,
        aisle: "Spices and Seasonings",
        image: "cinnamon.jpg",
        consistency: "SOLID",
        name: "cinnamon",
        nameClean: "cinnamon",
        original: "1/2 tsp cinnamon",
        originalName: "cinnamon",
        amount: 0.5,
        unit: "tsp",
        meta: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
      {
        id: 2025,
        aisle: "Spices and Seasonings",
        image: "ground-nutmeg.jpg",
        consistency: "SOLID",
        name: "nutmeg",
        nameClean: "nutmeg",
        original: "1/4 tsp nutmeg",
        originalName: "nutmeg",
        amount: 0.25,
        unit: "tsp",
        meta: [],
        measures: {
          us: {
            amount: 0.25,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.25,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
    ],
    id: 633548,
    title: "Baked Cinnamon Apple Wedges",
    readyInMinutes: 45,
    servings: 1,
    sourceUrl:
      "https://www.foodista.com/recipe/XJ3WCV8B/baked-cinnamon-apple-wedges",
    image: "https://spoonacular.com/recipeImages/633548-556x370.jpg",
    imageType: "jpg",
    summary:
      'Need a <b>gluten free, dairy free, paleolithic, and lacto ovo vegetarian side dish</b>? Baked Cinnamon Apple Wedges could be a great recipe to try. One portion of this dish contains approximately <b>1g of protein</b>, <b>1g of fat</b>, and a total of <b>120 calories</b>. For <b>87 cents per serving</b>, this recipe <b>covers 4%</b> of your daily requirements of vitamins and minerals. This recipe serves 1. If you have nutmeg, maple syrup, cinnamon, and a few other ingredients on hand, you can make it. It is brought to you by Foodista. 2 people were impressed by this recipe. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. Overall, this recipe earns a <b>not so amazing spoonacular score of 35%</b>. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/baked-cinnamon-apple-wedges-1369471">Baked Cinnamon Apple Wedges</a>, <a href="https://spoonacular.com/recipes/apple-cinnamon-baked-oatmeal-622523">Apple Cinnamon Baked Oatmeal</a>, and <a href="https://spoonacular.com/recipes/cinnamon-baked-apple-slices-1361101">Cinnamon Baked Apple Slices</a>.',
    cuisines: [],
    dishTypes: ["side dish"],
    diets: [
      "gluten free",
      "dairy free",
      "paleolithic",
      "lacto ovo vegetarian",
      "primal",
      "vegan",
    ],
    occasions: [],
    instructions:
      "Preheat oven to 180 degrees\nCut the apple into about 10-12 wedges and mix it with the rest of the ingredients.\nPlace the apple wedges in a small baking dish or on a baking tray  aim for a single layer.\nBake in the oven for 10 minutes. The apples should be golden brown and cooked all the way through.\nServe while warm.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Preheat oven to 180 degrees",
            ingredients: [],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
            ],
          },
          {
            number: 2,
            step: "Cut the apple into about 10-12 wedges and mix it with the rest of the ingredients.",
            ingredients: [
              {
                id: 9003,
                name: "apple",
                localizedName: "apple",
                image: "apple.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 3,
            step: "Place the apple wedges in a small baking dish or on a baking tray  aim for a single layer.",
            ingredients: [
              {
                id: 9003,
                name: "apple",
                localizedName: "apple",
                image: "apple.jpg",
              },
            ],
            equipment: [
              {
                id: 404646,
                name: "baking pan",
                localizedName: "baking pan",
                image: "roasting-pan.jpg",
              },
            ],
          },
          {
            number: 4,
            step: "Bake in the oven for 10 minutes. The apples should be golden brown and cooked all the way through.",
            ingredients: [
              {
                id: 9003,
                name: "apple",
                localizedName: "apple",
                image: "apple.jpg",
              },
            ],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
            ],
            length: {
              number: 10,
              unit: "minutes",
            },
          },
          {
            number: 5,
            step: "Serve while warm.",
            ingredients: [],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/baked-cinnamon-apple-wedges-633548",
  },
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 1,
    gaps: "no",
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 2,
    healthScore: 3,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 87.42,
    extendedIngredients: [
      {
        id: 9003,
        aisle: "Produce",
        image: "apple.jpg",
        consistency: "SOLID",
        name: "apple",
        nameClean: "apple",
        original: "1 apple",
        originalName: "apple",
        amount: 1.0,
        unit: "",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 1.0,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 19911,
        aisle: "Cereal",
        image: "maple-syrup.png",
        consistency: "LIQUID",
        name: "maple syrup",
        nameClean: "maple syrup",
        original: "1 tsp maple syrup",
        originalName: "maple syrup",
        amount: 1.0,
        unit: "tsp",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
          metric: {
            amount: 1.0,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
        },
      },
      {
        id: 2010,
        aisle: "Spices and Seasonings",
        image: "cinnamon.jpg",
        consistency: "SOLID",
        name: "cinnamon",
        nameClean: "cinnamon",
        original: "1/2 tsp cinnamon",
        originalName: "cinnamon",
        amount: 0.5,
        unit: "tsp",
        meta: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
      {
        id: 2025,
        aisle: "Spices and Seasonings",
        image: "ground-nutmeg.jpg",
        consistency: "SOLID",
        name: "nutmeg",
        nameClean: "nutmeg",
        original: "1/4 tsp nutmeg",
        originalName: "nutmeg",
        amount: 0.25,
        unit: "tsp",
        meta: [],
        measures: {
          us: {
            amount: 0.25,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.25,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
    ],
    id: 633549,
    title: "Baked Cinnamon Apple Wedges",
    readyInMinutes: 45,
    servings: 1,
    sourceUrl:
      "https://www.foodista.com/recipe/XJ3WCV8B/baked-cinnamon-apple-wedges",
    image: "https://spoonacular.com/recipeImages/633548-556x370.jpg",
    imageType: "jpg",
    summary:
      'Need a <b>gluten free, dairy free, paleolithic, and lacto ovo vegetarian side dish</b>? Baked Cinnamon Apple Wedges could be a great recipe to try. One portion of this dish contains approximately <b>1g of protein</b>, <b>1g of fat</b>, and a total of <b>120 calories</b>. For <b>87 cents per serving</b>, this recipe <b>covers 4%</b> of your daily requirements of vitamins and minerals. This recipe serves 1. If you have nutmeg, maple syrup, cinnamon, and a few other ingredients on hand, you can make it. It is brought to you by Foodista. 2 people were impressed by this recipe. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. Overall, this recipe earns a <b>not so amazing spoonacular score of 35%</b>. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/baked-cinnamon-apple-wedges-1369471">Baked Cinnamon Apple Wedges</a>, <a href="https://spoonacular.com/recipes/apple-cinnamon-baked-oatmeal-622523">Apple Cinnamon Baked Oatmeal</a>, and <a href="https://spoonacular.com/recipes/cinnamon-baked-apple-slices-1361101">Cinnamon Baked Apple Slices</a>.',
    cuisines: [],
    dishTypes: ["side dish"],
    diets: [
      "gluten free",
      "dairy free",
      "paleolithic",
      "lacto ovo vegetarian",
      "primal",
      "vegan",
    ],
    occasions: [],
    instructions:
      "Preheat oven to 180 degrees\nCut the apple into about 10-12 wedges and mix it with the rest of the ingredients.\nPlace the apple wedges in a small baking dish or on a baking tray  aim for a single layer.\nBake in the oven for 10 minutes. The apples should be golden brown and cooked all the way through.\nServe while warm.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Preheat oven to 180 degrees",
            ingredients: [],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
            ],
          },
          {
            number: 2,
            step: "Cut the apple into about 10-12 wedges and mix it with the rest of the ingredients.",
            ingredients: [
              {
                id: 9003,
                name: "apple",
                localizedName: "apple",
                image: "apple.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 3,
            step: "Place the apple wedges in a small baking dish or on a baking tray  aim for a single layer.",
            ingredients: [
              {
                id: 9003,
                name: "apple",
                localizedName: "apple",
                image: "apple.jpg",
              },
            ],
            equipment: [
              {
                id: 404646,
                name: "baking pan",
                localizedName: "baking pan",
                image: "roasting-pan.jpg",
              },
            ],
          },
          {
            number: 4,
            step: "Bake in the oven for 10 minutes. The apples should be golden brown and cooked all the way through.",
            ingredients: [
              {
                id: 9003,
                name: "apple",
                localizedName: "apple",
                image: "apple.jpg",
              },
            ],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
            ],
            length: {
              number: 10,
              unit: "minutes",
            },
          },
          {
            number: 5,
            step: "Serve while warm.",
            ingredients: [],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/baked-cinnamon-apple-wedges-633548",
  },
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 1,
    gaps: "no",
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 2,
    healthScore: 3,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 87.42,
    extendedIngredients: [
      {
        id: 9003,
        aisle: "Produce",
        image: "apple.jpg",
        consistency: "SOLID",
        name: "apple",
        nameClean: "apple",
        original: "1 apple",
        originalName: "apple",
        amount: 1.0,
        unit: "",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 1.0,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 19911,
        aisle: "Cereal",
        image: "maple-syrup.png",
        consistency: "LIQUID",
        name: "maple syrup",
        nameClean: "maple syrup",
        original: "1 tsp maple syrup",
        originalName: "maple syrup",
        amount: 1.0,
        unit: "tsp",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
          metric: {
            amount: 1.0,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
        },
      },
      {
        id: 2010,
        aisle: "Spices and Seasonings",
        image: "cinnamon.jpg",
        consistency: "SOLID",
        name: "cinnamon",
        nameClean: "cinnamon",
        original: "1/2 tsp cinnamon",
        originalName: "cinnamon",
        amount: 0.5,
        unit: "tsp",
        meta: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
      {
        id: 2025,
        aisle: "Spices and Seasonings",
        image: "ground-nutmeg.jpg",
        consistency: "SOLID",
        name: "nutmeg",
        nameClean: "nutmeg",
        original: "1/4 tsp nutmeg",
        originalName: "nutmeg",
        amount: 0.25,
        unit: "tsp",
        meta: [],
        measures: {
          us: {
            amount: 0.25,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.25,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
    ],
    id: 633550,
    title: "Baked Cinnamon Apple Wedges",
    readyInMinutes: 45,
    servings: 1,
    sourceUrl:
      "https://www.foodista.com/recipe/XJ3WCV8B/baked-cinnamon-apple-wedges",
    image: "https://spoonacular.com/recipeImages/633548-556x370.jpg",
    imageType: "jpg",
    summary:
      'Need a <b>gluten free, dairy free, paleolithic, and lacto ovo vegetarian side dish</b>? Baked Cinnamon Apple Wedges could be a great recipe to try. One portion of this dish contains approximately <b>1g of protein</b>, <b>1g of fat</b>, and a total of <b>120 calories</b>. For <b>87 cents per serving</b>, this recipe <b>covers 4%</b> of your daily requirements of vitamins and minerals. This recipe serves 1. If you have nutmeg, maple syrup, cinnamon, and a few other ingredients on hand, you can make it. It is brought to you by Foodista. 2 people were impressed by this recipe. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. Overall, this recipe earns a <b>not so amazing spoonacular score of 35%</b>. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/baked-cinnamon-apple-wedges-1369471">Baked Cinnamon Apple Wedges</a>, <a href="https://spoonacular.com/recipes/apple-cinnamon-baked-oatmeal-622523">Apple Cinnamon Baked Oatmeal</a>, and <a href="https://spoonacular.com/recipes/cinnamon-baked-apple-slices-1361101">Cinnamon Baked Apple Slices</a>.',
    cuisines: [],
    dishTypes: ["side dish"],
    diets: [
      "gluten free",
      "dairy free",
      "paleolithic",
      "lacto ovo vegetarian",
      "primal",
      "vegan",
    ],
    occasions: [],
    instructions:
      "Preheat oven to 180 degrees\nCut the apple into about 10-12 wedges and mix it with the rest of the ingredients.\nPlace the apple wedges in a small baking dish or on a baking tray  aim for a single layer.\nBake in the oven for 10 minutes. The apples should be golden brown and cooked all the way through.\nServe while warm.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Preheat oven to 180 degrees",
            ingredients: [],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
            ],
          },
          {
            number: 2,
            step: "Cut the apple into about 10-12 wedges and mix it with the rest of the ingredients.",
            ingredients: [
              {
                id: 9003,
                name: "apple",
                localizedName: "apple",
                image: "apple.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 3,
            step: "Place the apple wedges in a small baking dish or on a baking tray  aim for a single layer.",
            ingredients: [
              {
                id: 9003,
                name: "apple",
                localizedName: "apple",
                image: "apple.jpg",
              },
            ],
            equipment: [
              {
                id: 404646,
                name: "baking pan",
                localizedName: "baking pan",
                image: "roasting-pan.jpg",
              },
            ],
          },
          {
            number: 4,
            step: "Bake in the oven for 10 minutes. The apples should be golden brown and cooked all the way through.",
            ingredients: [
              {
                id: 9003,
                name: "apple",
                localizedName: "apple",
                image: "apple.jpg",
              },
            ],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
            ],
            length: {
              number: 10,
              unit: "minutes",
            },
          },
          {
            number: 5,
            step: "Serve while warm.",
            ingredients: [],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/baked-cinnamon-apple-wedges-633548",
  },
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 1,
    gaps: "no",
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 2,
    healthScore: 3,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 87.42,
    extendedIngredients: [
      {
        id: 9003,
        aisle: "Produce",
        image: "apple.jpg",
        consistency: "SOLID",
        name: "apple",
        nameClean: "apple",
        original: "1 apple",
        originalName: "apple",
        amount: 1.0,
        unit: "",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 1.0,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 19911,
        aisle: "Cereal",
        image: "maple-syrup.png",
        consistency: "LIQUID",
        name: "maple syrup",
        nameClean: "maple syrup",
        original: "1 tsp maple syrup",
        originalName: "maple syrup",
        amount: 1.0,
        unit: "tsp",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
          metric: {
            amount: 1.0,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
        },
      },
      {
        id: 2010,
        aisle: "Spices and Seasonings",
        image: "cinnamon.jpg",
        consistency: "SOLID",
        name: "cinnamon",
        nameClean: "cinnamon",
        original: "1/2 tsp cinnamon",
        originalName: "cinnamon",
        amount: 0.5,
        unit: "tsp",
        meta: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
      {
        id: 2025,
        aisle: "Spices and Seasonings",
        image: "ground-nutmeg.jpg",
        consistency: "SOLID",
        name: "nutmeg",
        nameClean: "nutmeg",
        original: "1/4 tsp nutmeg",
        originalName: "nutmeg",
        amount: 0.25,
        unit: "tsp",
        meta: [],
        measures: {
          us: {
            amount: 0.25,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.25,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
    ],
    id: 633551,
    title: "Baked Cinnamon Apple Wedges",
    readyInMinutes: 45,
    servings: 1,
    sourceUrl:
      "https://www.foodista.com/recipe/XJ3WCV8B/baked-cinnamon-apple-wedges",
    image: "https://spoonacular.com/recipeImages/633548-556x370.jpg",
    imageType: "jpg",
    summary:
      'Need a <b>gluten free, dairy free, paleolithic, and lacto ovo vegetarian side dish</b>? Baked Cinnamon Apple Wedges could be a great recipe to try. One portion of this dish contains approximately <b>1g of protein</b>, <b>1g of fat</b>, and a total of <b>120 calories</b>. For <b>87 cents per serving</b>, this recipe <b>covers 4%</b> of your daily requirements of vitamins and minerals. This recipe serves 1. If you have nutmeg, maple syrup, cinnamon, and a few other ingredients on hand, you can make it. It is brought to you by Foodista. 2 people were impressed by this recipe. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. Overall, this recipe earns a <b>not so amazing spoonacular score of 35%</b>. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/baked-cinnamon-apple-wedges-1369471">Baked Cinnamon Apple Wedges</a>, <a href="https://spoonacular.com/recipes/apple-cinnamon-baked-oatmeal-622523">Apple Cinnamon Baked Oatmeal</a>, and <a href="https://spoonacular.com/recipes/cinnamon-baked-apple-slices-1361101">Cinnamon Baked Apple Slices</a>.',
    cuisines: [],
    dishTypes: ["side dish"],
    diets: [
      "gluten free",
      "dairy free",
      "paleolithic",
      "lacto ovo vegetarian",
      "primal",
      "vegan",
    ],
    occasions: [],
    instructions:
      "Preheat oven to 180 degrees\nCut the apple into about 10-12 wedges and mix it with the rest of the ingredients.\nPlace the apple wedges in a small baking dish or on a baking tray  aim for a single layer.\nBake in the oven for 10 minutes. The apples should be golden brown and cooked all the way through.\nServe while warm.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Preheat oven to 180 degrees",
            ingredients: [],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
            ],
          },
          {
            number: 2,
            step: "Cut the apple into about 10-12 wedges and mix it with the rest of the ingredients.",
            ingredients: [
              {
                id: 9003,
                name: "apple",
                localizedName: "apple",
                image: "apple.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 3,
            step: "Place the apple wedges in a small baking dish or on a baking tray  aim for a single layer.",
            ingredients: [
              {
                id: 9003,
                name: "apple",
                localizedName: "apple",
                image: "apple.jpg",
              },
            ],
            equipment: [
              {
                id: 404646,
                name: "baking pan",
                localizedName: "baking pan",
                image: "roasting-pan.jpg",
              },
            ],
          },
          {
            number: 4,
            step: "Bake in the oven for 10 minutes. The apples should be golden brown and cooked all the way through.",
            ingredients: [
              {
                id: 9003,
                name: "apple",
                localizedName: "apple",
                image: "apple.jpg",
              },
            ],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
            ],
            length: {
              number: 10,
              unit: "minutes",
            },
          },
          {
            number: 5,
            step: "Serve while warm.",
            ingredients: [],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/baked-cinnamon-apple-wedges-633548",
  },
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 1,
    gaps: "no",
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 2,
    healthScore: 3,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 87.42,
    extendedIngredients: [
      {
        id: 9003,
        aisle: "Produce",
        image: "apple.jpg",
        consistency: "SOLID",
        name: "apple",
        nameClean: "apple",
        original: "1 apple",
        originalName: "apple",
        amount: 1.0,
        unit: "",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 1.0,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 19911,
        aisle: "Cereal",
        image: "maple-syrup.png",
        consistency: "LIQUID",
        name: "maple syrup",
        nameClean: "maple syrup",
        original: "1 tsp maple syrup",
        originalName: "maple syrup",
        amount: 1.0,
        unit: "tsp",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
          metric: {
            amount: 1.0,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
        },
      },
      {
        id: 2010,
        aisle: "Spices and Seasonings",
        image: "cinnamon.jpg",
        consistency: "SOLID",
        name: "cinnamon",
        nameClean: "cinnamon",
        original: "1/2 tsp cinnamon",
        originalName: "cinnamon",
        amount: 0.5,
        unit: "tsp",
        meta: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
      {
        id: 2025,
        aisle: "Spices and Seasonings",
        image: "ground-nutmeg.jpg",
        consistency: "SOLID",
        name: "nutmeg",
        nameClean: "nutmeg",
        original: "1/4 tsp nutmeg",
        originalName: "nutmeg",
        amount: 0.25,
        unit: "tsp",
        meta: [],
        measures: {
          us: {
            amount: 0.25,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.25,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
    ],
    id: 633552,
    title: "Baked Cinnamon Apple Wedges",
    readyInMinutes: 45,
    servings: 1,
    sourceUrl:
      "https://www.foodista.com/recipe/XJ3WCV8B/baked-cinnamon-apple-wedges",
    image: "https://spoonacular.com/recipeImages/633548-556x370.jpg",
    imageType: "jpg",
    summary:
      'Need a <b>gluten free, dairy free, paleolithic, and lacto ovo vegetarian side dish</b>? Baked Cinnamon Apple Wedges could be a great recipe to try. One portion of this dish contains approximately <b>1g of protein</b>, <b>1g of fat</b>, and a total of <b>120 calories</b>. For <b>87 cents per serving</b>, this recipe <b>covers 4%</b> of your daily requirements of vitamins and minerals. This recipe serves 1. If you have nutmeg, maple syrup, cinnamon, and a few other ingredients on hand, you can make it. It is brought to you by Foodista. 2 people were impressed by this recipe. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. Overall, this recipe earns a <b>not so amazing spoonacular score of 35%</b>. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/baked-cinnamon-apple-wedges-1369471">Baked Cinnamon Apple Wedges</a>, <a href="https://spoonacular.com/recipes/apple-cinnamon-baked-oatmeal-622523">Apple Cinnamon Baked Oatmeal</a>, and <a href="https://spoonacular.com/recipes/cinnamon-baked-apple-slices-1361101">Cinnamon Baked Apple Slices</a>.',
    cuisines: [],
    dishTypes: ["side dish"],
    diets: [
      "gluten free",
      "dairy free",
      "paleolithic",
      "lacto ovo vegetarian",
      "primal",
      "vegan",
    ],
    occasions: [],
    instructions:
      "Preheat oven to 180 degrees\nCut the apple into about 10-12 wedges and mix it with the rest of the ingredients.\nPlace the apple wedges in a small baking dish or on a baking tray  aim for a single layer.\nBake in the oven for 10 minutes. The apples should be golden brown and cooked all the way through.\nServe while warm.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Preheat oven to 180 degrees",
            ingredients: [],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
            ],
          },
          {
            number: 2,
            step: "Cut the apple into about 10-12 wedges and mix it with the rest of the ingredients.",
            ingredients: [
              {
                id: 9003,
                name: "apple",
                localizedName: "apple",
                image: "apple.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 3,
            step: "Place the apple wedges in a small baking dish or on a baking tray  aim for a single layer.",
            ingredients: [
              {
                id: 9003,
                name: "apple",
                localizedName: "apple",
                image: "apple.jpg",
              },
            ],
            equipment: [
              {
                id: 404646,
                name: "baking pan",
                localizedName: "baking pan",
                image: "roasting-pan.jpg",
              },
            ],
          },
          {
            number: 4,
            step: "Bake in the oven for 10 minutes. The apples should be golden brown and cooked all the way through.",
            ingredients: [
              {
                id: 9003,
                name: "apple",
                localizedName: "apple",
                image: "apple.jpg",
              },
            ],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
            ],
            length: {
              number: 10,
              unit: "minutes",
            },
          },
          {
            number: 5,
            step: "Serve while warm.",
            ingredients: [],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/baked-cinnamon-apple-wedges-633548",
  },
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 1,
    gaps: "no",
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 2,
    healthScore: 3,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 87.42,
    extendedIngredients: [
      {
        id: 9003,
        aisle: "Produce",
        image: "apple.jpg",
        consistency: "SOLID",
        name: "apple",
        nameClean: "apple",
        original: "1 apple",
        originalName: "apple",
        amount: 1.0,
        unit: "",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 1.0,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 19911,
        aisle: "Cereal",
        image: "maple-syrup.png",
        consistency: "LIQUID",
        name: "maple syrup",
        nameClean: "maple syrup",
        original: "1 tsp maple syrup",
        originalName: "maple syrup",
        amount: 1.0,
        unit: "tsp",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
          metric: {
            amount: 1.0,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
        },
      },
      {
        id: 2010,
        aisle: "Spices and Seasonings",
        image: "cinnamon.jpg",
        consistency: "SOLID",
        name: "cinnamon",
        nameClean: "cinnamon",
        original: "1/2 tsp cinnamon",
        originalName: "cinnamon",
        amount: 0.5,
        unit: "tsp",
        meta: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.5,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
      {
        id: 2025,
        aisle: "Spices and Seasonings",
        image: "ground-nutmeg.jpg",
        consistency: "SOLID",
        name: "nutmeg",
        nameClean: "nutmeg",
        original: "1/4 tsp nutmeg",
        originalName: "nutmeg",
        amount: 0.25,
        unit: "tsp",
        meta: [],
        measures: {
          us: {
            amount: 0.25,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
          metric: {
            amount: 0.25,
            unitShort: "tsps",
            unitLong: "teaspoons",
          },
        },
      },
    ],
    id: 633553,
    title: "Baked Cinnamon Apple Wedges",
    readyInMinutes: 45,
    servings: 1,
    sourceUrl:
      "https://www.foodista.com/recipe/XJ3WCV8B/baked-cinnamon-apple-wedges",
    image: "https://spoonacular.com/recipeImages/633548-556x370.jpg",
    imageType: "jpg",
    summary:
      'Need a <b>gluten free, dairy free, paleolithic, and lacto ovo vegetarian side dish</b>? Baked Cinnamon Apple Wedges could be a great recipe to try. One portion of this dish contains approximately <b>1g of protein</b>, <b>1g of fat</b>, and a total of <b>120 calories</b>. For <b>87 cents per serving</b>, this recipe <b>covers 4%</b> of your daily requirements of vitamins and minerals. This recipe serves 1. If you have nutmeg, maple syrup, cinnamon, and a few other ingredients on hand, you can make it. It is brought to you by Foodista. 2 people were impressed by this recipe. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. Overall, this recipe earns a <b>not so amazing spoonacular score of 35%</b>. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/baked-cinnamon-apple-wedges-1369471">Baked Cinnamon Apple Wedges</a>, <a href="https://spoonacular.com/recipes/apple-cinnamon-baked-oatmeal-622523">Apple Cinnamon Baked Oatmeal</a>, and <a href="https://spoonacular.com/recipes/cinnamon-baked-apple-slices-1361101">Cinnamon Baked Apple Slices</a>.',
    cuisines: [],
    dishTypes: ["side dish"],
    diets: [
      "gluten free",
      "dairy free",
      "paleolithic",
      "lacto ovo vegetarian",
      "primal",
      "vegan",
    ],
    occasions: [],
    instructions:
      "Preheat oven to 180 degrees\nCut the apple into about 10-12 wedges and mix it with the rest of the ingredients.\nPlace the apple wedges in a small baking dish or on a baking tray  aim for a single layer.\nBake in the oven for 10 minutes. The apples should be golden brown and cooked all the way through.\nServe while warm.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Preheat oven to 180 degrees",
            ingredients: [],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
            ],
          },
          {
            number: 2,
            step: "Cut the apple into about 10-12 wedges and mix it with the rest of the ingredients.",
            ingredients: [
              {
                id: 9003,
                name: "apple",
                localizedName: "apple",
                image: "apple.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 3,
            step: "Place the apple wedges in a small baking dish or on a baking tray  aim for a single layer.",
            ingredients: [
              {
                id: 9003,
                name: "apple",
                localizedName: "apple",
                image: "apple.jpg",
              },
            ],
            equipment: [
              {
                id: 404646,
                name: "baking pan",
                localizedName: "baking pan",
                image: "roasting-pan.jpg",
              },
            ],
          },
          {
            number: 4,
            step: "Bake in the oven for 10 minutes. The apples should be golden brown and cooked all the way through.",
            ingredients: [
              {
                id: 9003,
                name: "apple",
                localizedName: "apple",
                image: "apple.jpg",
              },
            ],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
            ],
            length: {
              number: 10,
              unit: "minutes",
            },
          },
          {
            number: 5,
            step: "Serve while warm.",
            ingredients: [],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/baked-cinnamon-apple-wedges-633548",
  },
];

export default data;
